SELECT PROFESSOR_NAME 교수이름,
   FLOOR(
   	MONTHS_BETWEEN(SYSDATE, 
   		TO_DATE('19' || SUBSTR(PROFESSOR_SSN, 1, 6),'YYYYMMDD')) /12) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 나이;
